include_recipe 'sprout-git::install'
include_recipe 'sprout-git::default_editor'
include_recipe 'sprout-git::global_ignore'
include_recipe 'sprout-git::aliases'
include_recipe 'sprout-git::global_config'
