include_recipe 'sprout-git::install'
include_recipe 'sprout-git::aliases'
include_recipe 'sprout-git::global_config'
include_recipe 'sprout-git::global_ignore'
include_recipe 'sprout-git::git_hooks'
include_recipe 'sprout-git::git_secrets'
