name             'sprout-git'
maintainer       'Pivotal'
maintainer_email 'sprout-maintainers@pivotallabs.com'
license          'MIT'
description      'Installs/Configures sprout-git'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.1'
supports         'mac_os_x'
depends          'sprout-base'
depends          'homebrew'
